name: caloria
description: A Hobby Flutter Project to track calories

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  intl: ^0.17.0
  expansion_tile_card: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
